apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web-dep
  namespace: bladex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
      - name: app-web
        image: app-web:1.0.0
        ports:
        - containerPort: 80
        #command: ["/bin/bash","-c","-"]
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-service
  labels:
    app: app-web
spec:
  #type: NodePort
  selector:
    app: app-web
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 30008