apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web-dep
  namespace: bladex
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
        - name: app-web
          image: app-web:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-web
  namespace: bladex
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-web