apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web-deployment
  namespace: bladex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web-service
  template:
    metadata:
      labels:
        app: app-web-deployment
    spec:
      containers:
      - name: k8s-app-web
        image: app-web:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-service
  namespace: bladex
  labels:
    app: app-web-service
spec:
  selector:
    app: app-web-deployment
  #type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30008
  ##type: NodePort
  #ports:
    #- protocol: TCP
    #  port: 80
    #  targetPort: 80