apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  namespace: bladex
spec:
  replicas: 1
  selector:
    name: app-web-pod
  template:
    metadata:
      labels:
        name: app-web-pod
    spec:
      containers:
      - name: k8s-app-web
        image: app-web:1.0.0
        ports:
        - containerPort: 80
