apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-memory
spec:
  limits:
 - default:            //默认使用0.5个cpu，512mi内存
      cpu: 0.1
      memory: 256Mi
    defaultRequest:       //默认要求0.1个cpu和256mi内存
      cpu: 0.1
      memory: 256Mi
    max:                //最大2个cpu和1gi内存
      cpu: 0.5
      memory: 512Gi
    min:               //最小0.1个cpu和100mi内存
      cpu: 0.1
      memory: 128Mi
    type: Container
