apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway-rc
  namespace: bladex
spec:
  replicas: 1
  selector:
    name: app-gateway-pod
  template:
    metadata:
      labels:
        name: app-gateway-pod
    spec:
      containers:
      - name: k8s-app-gateway
         image: app-gateway:1.0.0
         ports:
         - containerPort: 19999
