apiVersion: v1
kind: Pod
metadata:
  name: app-gateway-pod
  namespace: bladex
  labels:
    app: app-gateway
spec:
  containers:
  - name: k8s-app-gateway
    image: app-gateway:1.0.0
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 19999
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"