apiVersion: v1
kind: Service
metadata:
  name: app-auth-service
  namespace: bladex
spec:
  selector:
    name: app-auth-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
      nodePort: 38100