apiVersion: v1
kind: Pod
metadata:
  name: app-auth-pod
  namespace: bladex
  labels:
    app: app-auth
spec:
  containers:
  - name: k8s-app-auth
    image: app-auth-service:1.0.0
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 8100
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"