apiVersion: v1
kind: Service
metadata:
  name: app-sentinel-service
  namespace: bladex
  labels:
    app: app-sentinel-service
spec:
  type: NodePort
  ports:
  - port: 8858
    nodePort: 38858
    targetPort: 8858
    protocol: TCP
  selector:
    app: app-sentinel-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sentinel-service
  namespace: bladex
  labels:
    app: app-sentinel-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-sentinel-service
  template:
    metadata:
      labels:
        app: app-sentinel-service
    spec:
      #hostNetwork: true
      containers:
      - name: app-sentinel-pod
        image: 192.168.127.158:5000/app-sentinel-service:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PARAMES
          value: -Djava.security.egd=file:/dev/./urandom
        ports:
        - containerPort: 8858
        volumeMounts:
        - mountPath : /app/sentinel/logs
          name: log-vol
      volumes:
      - name: log-vol
        #emptyDir: {}
        hostPath:
          path: /home/logs/blade-sentinel