apiVersion: v1
kind: Service
metadata:
  name: dmo-app-system-service
  namespace: bladex
  labels:
    app: app-system-service
spec:
  ports:
  - port: 8106
    targetPort: 8106
    protocol: TCP
  selector:
    app: app-system-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-system-service
  namespace: bladex
  labels:
    app: app-system-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-system-service
  template:
    metadata:
      labels:
        app: app-system-service
    spec:
      #hostNetwork: true
      containers:
      - name: app-system-pod
        image: 192.168.127.158:5000/app-system-service:1.0.3
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_REDIS_HOST
          value: -Dspring.redis.host=192.168.127.134
        - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
          value: -Dspring.cloud.nacos.discovery.server-addr=192.168.127.154:38848
        - name: SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR
          value: -Dspring.cloud.nacos.config.server-addr=192.168.127.154:38848
        - name: BLADE_DATASOURCE_DEV_USERNAME
          value: -Dblade.datasource.dev.username=root
        - name: BLADE_DATASOURCE_DEV_PASSWORD
          value: -Dblade.datasource.dev.password=root
        - name: BLADE_DATASOURCE_DEV_URL
          value: -Dblade.datasource.dev.url="jdbc:mysql://192.168.127.133:3306/bladex?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 8106
        volumeMounts:
        - mountPath : /opt/applog
          name: my-volume
      volumes:
      - name: my-volume
        emptyDir: {}
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300