apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-rc
  namespace: bladex
spec:
  replicas: 1
  selector:
    name: app-redis-pod
  template:
    metadata:
      labels:
        name: app-redis-pod
    spec:
      containers:
      - name: k8s-app-redis
        image: chuabo/redis
        ports:
        - containerPort: 6379
