---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-redis-config
  namespace: bladex
data:
  redis-config:
    maxmemory 4mb
    maxmemory-policy allkeys-lru
    #requirepass 123
---
apiVersion: v1
kind: Pod
metadata:
  name: app-redis-pod
  namespace: bladex
  labels:
    app: app-redis
spec:
  containers:
  - name: k8s-app-redis
    image: chuabo/redis
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 6379
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: app-redis-service
  namespace: bladex
spec:
  selector:
    name: app-redis-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 36379