apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: bladex
  labels:
    app: redis-service
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 36379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  namespace: bladex
  labels:
    app: redis-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      #hostNetwork: true
      containers:
      - name: redis-pod
        image: chuabo/redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath : /opt/applog
          name: my-volume
      volumes:
      - name: my-volume
        emptyDir: {}